### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by Dylon0107** [TheOfficialFloW/crazytaxi_vita#10]
All I get is a black screen then error c2-12828-1 and a link to this file. it was a .psp2dmp file but i changed it to a .txt so i could upload it.

any known way to fix this issue?
[psp2core-1648140632-0x00002c20b5-eboot.bin.txt](https://github.com/TheOfficialFloW/crazytaxi_vita/files/8343769/psp2core-1648140632-0x00002c20b5-eboot.bin.txt)

**Comment by Rinnegatamante** [comment]
Use v.4.5 apk as specified in the release description.

**Comment by Dylon0107** [comment]
i have v4.5 apk and the other files are all set up as stated
