### ISSUE TITLE
Error: C2-12828-1

### ISSUE THREAD

**Issue by tatundria** [TheOfficialFloW/crazytaxi_vita#16]
After following the installation guide and copying all the files, I have an error while executing v1.2 of the vpk. It used to work with v1.1

Error is C2-12828-1
Saved Core File Succeeded
ux0:data/psp2core-1655285554-0x00005f276b-eboot.bin.psp2dmp

Any fix for this?

**Comment by Rinnegatamante** [comment]
Redownload the vpk. If it doesn't solve the issue then fault is on your side since the vpk has been tested with both 4.5 and 4.6 apks.

**Comment by tatundria** [comment]
I have already redownloaded it and it does not work. Any other idea?

**Comment by tatundria** [comment]
The funny thing is that I reinstalled apk v1.1 with Crazy Taxi v4.5 and it works.

Please, can you check if there is any fix for apk v1.2 and with Crazy Taxi v4.6?
