### ISSUE TITLE
Cannot Build From Source

### ISSUE THREAD

**Issue by MystiK791** [TheOfficialFloW/crazytaxi_vita#17]
Hello!
I wanted to play around with this code some, and see if I could get any other games running with the loader. I thought I'd try building this project from source before making any modifications to verify everything is set up OK. However, I keep getting an error during compilation:

/mnt/c/msys64/home/techg/crazytaxi_vita/loader/main.c:121:5: error: conflicting types for 'clock_gettime'
  121 | int clock_gettime(int clk_id, struct timespec *tp) {
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/rtc.h:11,
                 from /mnt/c/msys64/home/techg/crazytaxi_vita/loader/main.c:19:
/usr/local/vitasdk/arm-vita-eabi/include/time.h:167:5: note: previous declaration of 'clock_gettime' was here
  167 | int clock_gettime (clockid_t clock_id, struct timespec *tp);

I'm using WSL2 to compile, and I have all the dependencies built from source, just as directed in the compilation instructions. What's going on here?

**Comment by MystiK791** [comment]
I fixed it by renaming the function to clock_get_time, meaning it's most likely a problem with the code.

**Comment by MystiK791** [comment]
I get to the point where the compiler is linking the executable, and then this happens:
[error.txt](https://github.com/TheOfficialFloW/crazytaxi_vita/files/8992851/error.txt)

Like I said, I know my VitaSDK installation works properly.

**Comment by Rinnegatamante** [comment]
There are instructions on how to build this in the README.

**Comment by Rinnegatamante** [comment]
You are not since you're using an hardfp vitasdk.

**Comment by MystiK791** [comment]
> You are not since you're using an hardfp vitasdk.

Whoops... guess I overlooked that. I'll try rebuilding once I get that fixed.
