### ISSUE TITLE
After update, the version didn't change (Version 1.1) 

### ISSUE THREAD

**Issue by SofyUchiha** [TheOfficialFloW/crazytaxi_vita#8]
I installed the vpk from the latest update, but the version hasn't changed in the app info. Is it a bug? 
![image](https://user-images.githubusercontent.com/70182567/159092872-6c621d54-5044-4245-9462-5f5b755ab47e.png)
PD: Thanks a lot for your work, I love the port!

**Comment by Rinnegatamante** [comment]
The versioning in APP_INFO is basically never changed for almost every single homebrew.
